version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: "database"
        POSTGRES_USER: "docker"
        POSTGRES_PASSWORD: "docker"
    volumes:
      - /mnt/d/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080
    
  app:
    image: youngmukde/festa-python:latest
    volumes:
      - /mnt/c/Users/admin/miraeasset-festa/DataEngineering/srcs:/app/srcs
    working_dir: /app/srcs
    command: tail -f /dev/null

volumes:
  dbdata:
