name: Publish Docker Image

on:
  push:
    branches: ['main']
    tags: ['*']
    paths:
      - 'DataEngineering/srcs/api/kis/**'

jobs:
  push_to_registry:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Build and push KIS image
        uses: docker/build-push-action@v2
        with:
          context: kis
          file: DataEngineering/srcs/api/kis/Dockerfile
          tags: youngmki/kis_api:${{ steps.extract_tag.outputs.tag }}