name: "[CI] naver"

on:
  push:
    branches: ['main']
    tags: ['*']
    paths:
      - 'DataEngineering/srcs/api/naver/**'

jobs:
  push_to_registry:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch or tag name
        id: extract_ref
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TYPE=tag" >> $GITHUB_ENV
            echo "REF_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TYPE=branch" >> $GITHUB_ENV
            echo "REF_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Build and push NAVER image
        uses: docker/build-push-action@v2
        with:
          context: DataEngineering/srcs
          file: DataEngineering/srcs/api/naver/Dockerfile
          tags: youngmki/naver_api:${{ env.REF_NAME }}
