name: "🐳 [CI] naver"

on:
  push:
    branches: ['main']
    tags: ['*']
    paths:
      - 'DataEngineering/srcs/api/naver/**'

jobs:
  push_to_registry:
    name: ⚡ push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: ⚡ login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: ⚡ Build and push NAVER image
        uses: docker/build-push-action@v2
        with:
          context: DataEngineering/srcs
          file: DataEngineering/srcs/api/naver/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
